# Generated by Django 5.2 on 2025-05-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfmapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('upcoming', 'upcoming')], default='upcoming', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('excepted_durations', models.PositiveIntegerField(help_text='duraiton in days')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='wfmapi.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.project')),
            ],
            options={
                'unique_together': {('project', 'group')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(related_name='projects', through='wfmapi.ProjectGroup', to='wfmapi.group'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.worker')),
            ],
            options={
                'unique_together': {('project', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(related_name='projects', through='wfmapi.ProjectWorker', to='wfmapi.worker'),
        ),
        migrations.CreateModel(
            name='GroupWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.group')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfmapi.worker')),
            ],
            options={
                'unique_together': {('group', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='workers',
            field=models.ManyToManyField(related_name='groups', through='wfmapi.GroupWorker', to='wfmapi.worker'),
        ),
    ]
