# Generated by Django 5.2 on 2025-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfmapi', '0002_client_group_project_projectgroup_project_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='excepted_durations',
        ),
        migrations.AddField(
            model_name='project',
            name='expected_duration',
            field=models.PositiveIntegerField(default=3, help_text='duration in days'),
        ),
    ]
