# Generated by Django 5.2 on 2025-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfmapi', '0003_remove_project_excepted_durations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
            preserve_default=False,
        ),
    ]
